### ISSUE TITLE
16.04.2022

### ISSUE THREAD

**Issue by pmascaraque** [deepman42/Spacex-Api#1]
### Code Review

1. Vercel Deployment not working.
2. READMEs
3. Empty File
4. Indentation & prettier
5. Remove Create-React-App Title.
6. Github Labels, Tags and Documentation for Stack (IE: chakra-ui, react, node, vercel, etc)
7. Clean package.json

Looks great, I urge you to work more on it and make it a full fledged app!

**Comment by isleyva** [comment]
Done!
